version: "2"
linters:
  enable:
    - revive
  settings:
    revive:
      rules:
        - name: exported
          severity: error
        - name: package-comments
          severity: error
    staticcheck:
      checks:
        - all # Include all checks by default
        - "-SA1019" # Exclude the SA1019 (deprecated) check until full migration to CAPI v1beta2
        - "-QF1008" # Exclude the QF1008 (could remove embedded field) check until further refactoring
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
